apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-emd-test
  namespace: ns-emd-test
spec:
  distribution:
    version: v1.21
  topology:                               
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: kubernetes-storage-policy
    workers:                              
      count: 1
      class: best-effort-xsmall
      storageClass: kubernetes-storage-policy
  settings: #all spec.settings are optional
    storage: #optional storage settings
      classes: [kubernetes-storage-policy]
      defaultClass: kubernetes-storage-policy
    network: #optional network settings
      cni: #override default cni set in the tkgservicesonfiguration spec
        name: antrea
      pods: #custom pod network
        cidrBlocks: [172.22.0.0/24]
      services: #custom service network
        cidrBlocks: [172.23.0.0/24]