apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tau-tkc1
  namespace: tau-ns1
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-large
      storageClass: kubesp
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: worker-nodepool-a1
      replicas: 3
      vmClass: best-effort-large
      storageClass: kubesp
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
