apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vmsvc-rocky-vm
  namespace: namespace-emd
spec:
  imageName: ubuntu-20-1633387172196
  className: rocky-emd
  powerState: poweredOn
  storageClass: kubernetes-demo-storage-policy
