apiVersion: v1
kind: Pod
metadata:
  name: gs-private-reg
spec:
  containers:
  - name: gs-private-reg-container
    image: http://harbor.tanzu.rams.adp.vcu.edu/test/getting-started
  imagePullSecrets:
  - name: gs-secret